spring.datasource.url=jdbc:postgresql://localhost:5432/bip
spring.datasource.username=bip
spring.datasource.password=bip
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
#spring.sql.init.schema-locations=file:../db/schema.sql
#spring.sql.init.data-locations=file:../db/seed.sql